name: Build and publish Docker image

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

permissions:
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to Container registry
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ghcr.io/rakino/misskey:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
